apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-store-clusterrolebinding-{{ .Values.env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-store-clusterrole-{{ .Values.env }}
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-store.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}